# GitHub Actions workflow for Continuous Integration and Continuous Deployment (CI/CD)
name: cicd

# Trigger the workflow on push to main branch and pull requests to main and dev branches
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - main
      - dev 
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Use personal access token instead of GITHUB_TOKEN
          fetch-depth: 0 # Fetch all history for all branches and tags
      
      # Step 2: Set up Go environment
      - name: Get Go version from Dockerfile
        id: get-go-version
        run: |
          GO_VERSION=$(sed -n 's/FROM golang:\([0-9.]*\).*/\1/p' Dockerfile)
          echo "version=$GO_VERSION" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.get-go-version.outputs.version }}
          
      # Step 3: Build the Go code
      - name: Build the code
        run: |
          if go build -v ./...; then
            echo "Build successful"
          else
            echo "Build failed"
            exit 1
          fi

      # Step 4: Build and push Docker image
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.ref_name }}-${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.ref_name }}-${{ github.sha }}

      # Step 5: Update Helm chart values with new image tag
      - name: Update Helm values 
        run: |
          sed -i 's|tag:.*|tag: "${{ github.ref_name }}-${{ github.sha }}"|' go-web-app-chart/values.yaml

      # Step 6: Authenticate Git with access token (incomplete command)
      - name: Login to Git with access token
        run: |
           git lo  # Note: This command is incomplete and needs to be fixed

      # Step 7: Commit and push changes to the repository
      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: update helm chart with new image tag
          target_branch: main
